### ISSUE TITLE
Which sen2like options to enable

### ISSUE THREAD

**Issue by ValentinaHutter** [senbox-org/sen2like#6]
We are working on integrating `sen2like` as an `openEO process` into `openEO Platform`. The approach is to also allow the options in the `config.ini` to be set to `True`, or `False` by the user. The possible options right now are all set to `True` per default: 

``` options = {
    "doGeometry": True, 
    "doStitching": True,
    "doGeometryCheck": True, 
    "doToa": True, 
    "doInterCalibration": True, 
    "doAtmcor": True, 
    "doNbar": True, 
    "doSbaf": True} 
```
We are now wondering, if there are specific combinations of options set to `False`, which we do not want to allow or which might not make sense for the `L2H` or `L2F` product? 
Thanks in advance!

**Comment by telespazio-tim** [comment]
Hi Valentina,

All theses options MUST be set to `True` for L2H and L2F generation.
We use them to switch on/off sen2like processing blocks for tests or experimentation purpose.

Regards

**Comment by christophreimer** [comment]
of interest for @patrick-griffiths

**Comment by patrick-griffiths** [comment]
@telespazio-tim 
so you would suggest to not expose any of these to the user as optional parameters?
If for example the NBAR or SBAF were optional it would clearly be an added value to the user, 
to activate them optionally...

**Comment by telespazio-tim** [comment]
We wanted to highlight that to get an harmonized product, it is required to activate all the processing blocks, in this way there is no sense to deactivate a processing block.
However we agree with you that it can be useful for the user to activate or not some proc blocks for other purposes.
Also notice that the quality report in the product allow to know what processes have been applied to the input product.

**Comment by patrick-griffiths** [comment]
@telespazio-tim 
remember that we are exposing sen2like in openEO in two ways: 
1) product based batch processing via GUI (here all parameter should be set to default values) 
2) sen2like as part of a larger openEO workflow, where optional parametrization would be valuable.

Therefore it would be good to know for which params it would make sense to expose them?
Interesting candidates would be: doNbar, do Sbaf

**Comment by telespazio-tim** [comment]
We think that Sbaf process should always be done.
Here is a list of parameters that we think users could manage : 

- For processing blocks : 

`doNbar`

Of course, you're free to add other processing block activation parameters.
But to have good fusion results, we highly recommend to keep them all activated.

`doStitching` could also be candidate, but it is interesting keep it always activated because it allows to fill as much as possible MGRS tile of the image to produce.

Notice that `doGeometryCheck` have no impact on produced band images. It only allows to fill geo correction information in the quality report file `L2H/F_QUALITY.xml`

- Other parameters: 

`coverage`
`cloud_cover`
`reference_band`
`doMatchingCorrection`
`doAssessGeometry`
`force_geometric_correction`
`predict_method`
`predict_nb_products`
`fusion_auto_check_band`
`fusion_auto_check_threshold`
`same_utm_only`

Assuming you are integrating sen2like v4.2, you'll find the description of each of them [here](https://github.com/senbox-org/sen2like/blob/v4.2.0/sen2like/README.md#configuration-file)
